Added undo / redo stack for cropper
wulkano/Kap pull request #1004
Opened 2021-04-23 00:17 UTC by lescobar723

I added a stack to keep track of each cropper state whenever the cropper is adjusted or edited. The user can now press the 'z' key for undo or 'y' key for redo and the cropper will be adjusted accordingly. 

This added feature is in response to #976

2021-04-23 05:52 UTC, sindresorhus commented
It should use Shift+Command+Z to redo. That's the convention on macOS.

2021-04-23 05:57 UTC, sindresorhus requested changes

2021-04-23 05:57 UTC, sindresorhus commented on renderer/containers/cropper.js
> +      this.setState({cropperPointer: currPointer});
I think it would be better to use a single setState call.

2021-04-23 05:57 UTC, sindresorhus commented on renderer/containers/cropper.js
> +    if (this.state.cropperPointer > 0) {
Use early-return.

2021-04-23 05:57 UTC, sindresorhus commented on renderer/containers/cropper.js
> +      const currPointer = this.state.cropperPointer + 1;
Don't use abbreviations.

2021-04-23 05:57 UTC, sindresorhus commented on renderer/containers/cropper.js
> +      undone: false,
`isUndone`

2021-04-23 05:57 UTC, sindresorhus commented
Would have been nice if the all the undo-related logic would go into a `UndoManager` class.

2021-04-23 06:02 UTC, skllcrn commented
Thank you! Great first commit. I'm curious about you reasoning for going with <kbd>Z<kbd> and <kbd>Y<kbd> over <kbd>Command<kbd> + <kbd>Z<kbd> to undo, <kbd>Command<kbd> + <kbd>Shift<kbd> + <kbd>Z<kbd> to redo?

2021-04-23 15:24 UTC, lescobar723 commented
Hello, thank you for the response! I will try to make the new changes, but I am new to using Electron and React so it will take me a bit but I am up for the challenge! I used the 'z' and 'y' keys for undo and redo because I noticed in the function handleKeyEvent function in the cropper.js file in the pages directory whenever you press one of the keys that are in either in Command+Z and Command+Z+Shift, it really depends on which of those keys you pressed first. Let's say you pressed Shift first in the Command+Z+Shift combination then in the cropper.js file it will go into the Shift case regardless on if you pressed more keys. You cannot really tell the order in which the user will press keys in so I was thinking maybe for multiple key presses the single key cases in handleKeyEvent is not very suitable. So I will try to find a fix to that, one solution is mentioned [here](https://stackoverflow.com/questions/5203407/how-to-detect-if-multiple-keys-are-pressed-at-once-using-javascript). 

Any other suggestions would be greatly appreciated.

2021-04-27 10:54 UTC, sindresorhus requested changes

2021-04-27 10:54 UTC, sindresorhus commented on renderer/pages/cropper.js
> +let metaKeyDown = false;
```suggestion
let iaMetaKeyDown = false;
```

2021-04-27 10:54 UTC, sindresorhus commented on renderer/pages/cropper.js
> +let ShiftDown = false;
```suggestion
let iaShiftKeyDown = false;
```

2021-04-27 10:54 UTC, sindresorhus commented on renderer/pages/cropper.js
> +        if (metaKeyDown && ShiftDown) {
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/shiftKey

2021-04-27 10:54 UTC, sindresorhus commented on renderer/containers/cropper.js
> +  undo = () => {
There's a lot of duplicated logic between the `undo` and `redo` methods. I would try to unify the logic into an internal method which both of these call.

2021-04-27 10:54 UTC, sindresorhus commented on renderer/containers/cropper.js
> +      const CropperHistoryLength = this.state.cropperHistory.length;
```suggestion
      const cropperHistoryLength = this.state.cropperHistory.length;
```

2021-04-27 10:57 UTC, sindresorhus commented
Have you looked into using something like https://github.com/frontendphil/react-undo-redo or https://github.com/homerchen19/use-undo ?

2022-08-09 00:54 UTC, sindresorhus commented
Closing for lack of response.

2022-08-09 17:44 UTC, closed without merging